## Things I learned doing AoC 2023

This is just to document random Python things I have learned from doing AoC 2023

#### You can use Booleans to see if a substring is inside a string

In [1]:
#use this tactically with the AoC inputs if there are specific things you have to look out for
'abc' in 'abcdefg'

True

#### The product iterator

In [3]:
#I've never heard of itertools in my life. Happy I have now!
#This looks especially useful for finding the neighbours of indicies.

from itertools import product

for i in product(range(-1, 2), range(-1, 2)):
    print(i)

(-1, -1)
(-1, 0)
(-1, 1)
(0, -1)
(0, 0)
(0, 1)
(1, -1)
(1, 0)
(1, 1)


#### Some Numpy array things

In [2]:
import numpy as np

arr = np.array([1,1,2,3,4,4,5])

#np.unique gives you an array that shows you all the unique elements in the array
unique_arr = np.unique(arr)
print(unique_arr)

[1 2 3 4 5]


#### the ord() function

In [7]:
#technically day 12 of 2022....
#This gives us the ability to get the ascii value of a string:

print('.:',ord('.'))
print('a:',ord('a'))
print('A:',ord('A'))
print('1:',ord('1'))

.: 46
a: 97
A: 65
1: 49


#### Numpy matrix multiplication

In [9]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

np.matmul(arr1, arr2)

array([[ 7, 10],
       [15, 22]])

In [12]:
#what if I want to do a product?

arr1 = np.array([[1,2],[3,4]])

for i in range(10):
    arr1 = np.matmul(arr1,[[1,1],[1,0]])

    print(arr1)

[[3 1]
 [7 3]]
[[ 4  3]
 [10  7]]
[[ 7  4]
 [17 10]]
[[11  7]
 [27 17]]
[[18 11]
 [44 27]]
[[29 18]
 [71 44]]
[[ 47  29]
 [115  71]]
[[ 76  47]
 [186 115]]
[[123  76]
 [301 186]]
[[199 123]
 [487 301]]


In [14]:
#what if I want to keep multiplying the matrix by itself?

arr1 = np.array([[1,2],[3,4]])
product_matrix = np.zeros((2,2)) + arr1

for i in range(3):
    product_matrix = np.matmul(arr1,product_matrix)

    print(product_matrix)

[[ 7. 10.]
 [15. 22.]]
[[ 37.  54.]
 [ 81. 118.]]
[[199. 290.]
 [435. 634.]]
